### PR TITLE
Null instance error

### PR DESCRIPTION
**Pull request by max-koro**
```
get_tile():
	return $Tile.get_collider()
```

`.get_collider()` returns "null" if no object is intersecting the ray
This triggered a null instance error for me
image

Maybe I missed something, please let me know if I did :)
Since your test_level is not throwing an error, it's highly likely I did

### CODE REVIEW

**Comment by max-koro** [comment]
I suspect it has to do with pawn placement, but I used snap to grid and placed them right above the tiles so that's why I assumed it was a code issue. However in the render, the characters show floating above the actual tiles (after my code edits)
image
image

**Comment by max-koro** [comment]
Another important note:

I'm using Godot 4's native support of `.blend` files to directly import the terrain & tile nodes into the arena scene.
I do it this way because the Godot export plugin is causing issues for me ( = squashing all terrain or all tiles into 1 cube, despite following your tutorial religiously)

**Comment by ramaureirac** [comment]
Hi @mbusson,

Yes! all characters must stay above a tile (raycasting) else is impossible to create a route for them. Therefore returning `null instance` is an expected (but not desired) error. 

`adjust_to_center` function is suppose to fix this issue at the begging of the battle and after any movement. However, it seems not to be working as expected on certain scenarios [1].

Will it be possible to have a copy of your scene and blender files for testing?

Thanks,

[1] [Another similar issue](https://github.com/ramaureirac/godot-tactical-rpg/issues/8)

**Comment by max-koro** [comment]
Hi @ramaureirac ! Thanks for jumping on this so quickly 🙏 

Here are the required files 😄 
[ramaureirac.zip](https://github.com/user-attachments/files/16111174/ramaureirac.zip)

Blender file:
- Origin to Geometry looks to be properly applied
image
- Could the fact [I use `.blend` files directly](https://github.com/ramaureirac/godot-tactical-rpg/pull/13#issuecomment-2209446772) without the exporter plugin be the issue?

Let me know if you need anything else :)

**Comment by eimfach** [comment]
I think it is an issue with the physics server not being ready at load time. It is better to set the starting tile in the pawn class as an export and then apply the movings of the pawn when the ray actually collides (is not null anymore). At least this is what I did. You have to account for the Tile Meshes being converted to StaticBodies during runtime though.

**Comment by ramaureirac** [comment]
Hello @mbusson,

I manage to test your level and code. Just mention I wasn't able to import the `mountain-base_arena.tscn` file so had to recreate it using the template file. As @eimfach said this is strongly related to godot's physics server during the start of the scene.

By using your code found that `adjust_to_center ` function seems to fail when is not strictly aligned to a tile center. I fact I noticed some pawns may detect something and "spawn" on a non desired location.

Initial position:
image

Result (knight and archer):
image

I write a small a fix for this by changing the `adjust_to_center ` logic and also call it after the `_ready` function:
image

I'll leave this on a separate [branch](https://github.com/ramaureirac/godot-tactical-rpg/tree/feature/13-fix-null-instance-error) in case you wanna review it.

In any case @eimfach solution is definitely better, especially if you are creating a battle from another scene. It makes more sense to parse the tile directly instead of a random position.

Since I had to recreate the whole arena scene I'll put the steps of what I did in here:
- Duplicate test_arena.tscn
- Remove Tiles and Terrain
- Drag and drop blender file
- Right clic on blender node and clic on "Make Local"
- Move Terrain node outside blender node
- Rename blender node as "Tiles"

Hope this helps

**Comment by max-koro** [comment]
> It is better to set the starting tile in the pawn class as an export and then apply the movings of the pawn when the ray actually collides (is not null anymore). At least this is what I did. You have to account for the Tile Meshes being converted to StaticBodies during runtime though.

Thank you @eimfach ! Do you have an example of how you did this by any chance? :)

I'm new to Godot & GDScript, I don't know how I can get a Tile node from `Arena.tscn` into the Level scene editor 🤐 (i.e. how to import across scenes, Arena Tile => Level Pawn)

`@export var starting_tile : TacticTile` only lets me pull nodes from the Level scene into the Pawn Inspector:

image

<hr>

> I'll leave this on a separate [branch](https://github.com/ramaureirac/godot-tactical-rpg/tree/feature/13-fix-null-instance-error) in case you wanna review it.

Thanks @ramaureirac ! I've been testing it today, it's working great 🙌 

I forgot to tell you I am on `4.3-beta2` 🤦‍♂️  That's probably why the scene format wasn't parsed by your Godot client

I'm closing this PR since it's not needed anymore; thank you for your help! 
Let me know if you're looking for help on this project, I could use a mentor on Godot stuff if you want my time & code 😄

**Comment by eimfach** [comment]
I think you need to enable "Editable Children" to access the tiles. Can't verify at the moment because I am off the pc. Just remember that the path to the tile your are setting for the pawn will not exist anymore during runtime, instead there will be a Static Body in it's place and the Tile a child of it. 

When I have access to my pc again, I can show you how I did it.

If you are a complete beginner, I recommend you to read a lot in the Godot docs from the very beginning about how things work.

Also a possible solution might be to move tile related things in the Pawn to the `physics_process` override and/or guard with a null check before the Pawn is placed on the Tile. It's just that in the beginning of the game, the collision layers are not there, because it is generated during runtime in the `ready` event. Once this is done you can also await some physics frames and then send a signal to the level controller that calls the pawn to place itself on the tile. If it's null then, I'd let it crash and see what you need to fix.

**Comment by max-koro** [comment]
Cheers, editable children did the trick!

Yes - I'd definitely be interested in reading how you programmed your approach if it's not too much trouble to share :)

Thanks for the advice as well, I come from web dev so I have a lot of game dev specific stuff to learn (I spent a bunch of years on RPG Maker but those don't count 🤣)

If you have recommendations for helpful material, I'll happily take it! I think the most useful resources I came across thus far was Brackey's guide to GDScript, as well as GDQuest obviously. The official Godot Docs are quite concept-heavy, sometimes under-documented and often overwhelming, so I can't stay focused on bulk reading it for too long

Your last paragraph makes a lot of sense! Thanks again 😄

**Comment by ramaureirac** [comment]
> Thanks @ramaureirac ! I've been testing it today, it's working great 🙌

Glad to hear it! I'm moving all new code into development branch then.

> Let me know if you're looking for help on this project, I could use a mentor on Godot stuff if you want my time & code 😄, 

All help is always appreciated. If you have a suggestion or feature you can post it in here or write me directly so we can talk about it (it is sad reject a PR just because it is not fully aligned with the main idea. In such cases it is better to start a fork). 

I was thinking on implementing the tile stuff, but if you want to do it it's all yours 😄 .

Thanks again @mbusson @eimfach !!

**Pull request closed without merging**
