### PR TITLE
Input capture refactor

### PR DESCRIPTION
**Pull request by max-koro**
I think I'm all done!
Now it's gonna be very easy to add input mapping abstractions in this central class, etc.

Do you have any strong opinions about the special case of `"ui_accept"`?
I think it is such a universal and situational input, it doesn't need any extra abstraction layer. Especially since it's very easy to call it as-needed with `Input.is_action_just_pressed("ui_accept")`. So I didn't migrate this specific input capture into our new class, but I'm open to feedback!

### CODE REVIEW

**Comment by ramaureirac** [comment]
look good, probably i'm going to review this weekend,
qq: are we still using "ui_accept" for selecting pawns ?

**Comment by max-koro** [comment]
> look good, probably i'm going to review this weekend, qq: are we still using "ui_accept" for selecting pawns ?

Sounds good!
Yes, we are :)

**Comment by max-koro** [comment]
I added extra changes to the MR:
- Debug improvement: centralized debug config options into a single dictionary, made logging behaviour dependent on the "type" prop of said object
- Renamed all master services for easier in-editor identification

Btw you might want to replace the ugly wiki link I added in the readme with an image that fits your theme :)

**Review by ramaureirac — APPROVED** [review]
lgtm

**Pull request merged**
